'use strict';
const $ = id => document.getElementById(id);
let lang = 'ar', position = null, storageOK = true;
const key = 'waqood-demo-v1';
let saved = {favorites:[], reports:[], epoch:Date.now()};
try { const parsed = JSON.parse(localStorage.getItem(key)); if(parsed && Array.isArray(parsed.favorites) && Array.isArray(parsed.reports) && Number.isFinite(parsed.epoch)) saved = parsed; } catch { storageOK = false; }
const stations = seedStations.map((s,i)=>({...s, open:i!==4, wait:[8,25,65,12,null,8][i], timestamp:saved.epoch-[5,12,3,18,35,10][i]*60000}));
function t(ar,en){return lang==='ar'?ar:en;}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function name(s){return s['name_'+lang];}
function age(s){return Math.max(0,Math.floor((Date.now()-s.timestamp)/60000));}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));storageOK=true;return true;}catch{storageOK=false;return false;}}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,6500);}
function distance(s){if(!position)return Infinity;const rad=x=>x*Math.PI/180;const a=Math.sin(rad(s.lat-position.lat)/2)**2+Math.cos(rad(position.lat))*Math.cos(rad(s.lat))*Math.sin(rad(s.lng-position.lng)/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(Math.max(0,1-a)));}
function filtered(){const q=$('search').value.trim().toLowerCase(),fuel=$('fuel').value;return stations.filter(s=>(s.name_ar+' '+s.name_en+' '+s.area_ar+' '+s.area_en).toLowerCase().includes(q)&&(fuel==='all'||s[fuel])&&(!$('openOnly').checked||s.open)&&(!$('savedOnly').checked||saved.favorites.includes(s.id))).sort((a,b)=>$('sort').value==='near'?distance(a)-distance(b):$('sort').value==='fresh'?b.timestamp-a.timestamp:(a.wait??Infinity)-(b.wait??Infinity));}
function stat(value,label){return `<div class="stat"><strong>${value}</strong><span>${label}</span></div>`;}
function render(){const open=stations.filter(s=>s.open),stale=stations.filter(s=>age(s)>30);$('summary').innerHTML=stat(stations.length,t('محطات في الدليل','Stations in directory'))+stat(open.length,t('محطات مفتوحة','Stations open'))+stat(open.filter(s=>s.wait<=15).length,t('انتظار ١٥ دقيقة أو أقل','Wait of 15 min or less'))+stat(stale.length,t('تحديثات تحتاج تأكيداً','Updates needing confirmation'));
const items=filtered();$('resultCount').textContent=t(`${items.length} محطات مطابقة`,`${items.length} matching stations`);
$('cards').innerHTML=items.length?items.map(s=>`<article class="station"><div class="station-top"><span class="pill ${s.open?'':'closed'}">${s.open?t('● مفتوحة','● Open'):t('● مغلقة','● Closed')}</span><button class="favorite" data-save="${s.id}" aria-pressed="${saved.favorites.includes(s.id)}" aria-label="${esc(t('حفظ ','Save ')+name(s))}">${saved.favorites.includes(s.id)?'★':'☆'}</button></div><h3>${esc(name(s))}</h3><div class="area">${esc(s['area_'+lang])} · ${esc(s['company_'+lang])}</div><div class="wait"><strong>${s.open?s.wait:'—'}</strong><span>${s.open?t('دقيقة انتظار تقريباً','min estimated wait'):t('الانتظار غير متاح','Wait unavailable')}</span></div><div class="fuels"><span class="${s.gas95?'':'unavailable'}">${s.gas95?'✓':'−'} ${t('بنزين 95','Gasoline 95')} · ${s.gas95?t('متوفر','Available'):t('غير متوفر','Unavailable')}</span><span class="${s.diesel?'':'unavailable'}">${s.diesel?'✓':'−'} ${t('ديزل','Diesel')} · ${s.diesel?t('متوفر','Available'):t('غير متوفر','Unavailable')}</span></div><div class="updated ${age(s)>30?'stale':''}">${t('بيانات نموذجية · منذ ','Sample data · ')}${age(s)} ${t('دقيقة','min ago')}${age(s)>30?' · '+t('تحتاج تأكيداً','Needs confirmation'):''}${position?'<br>'+distance(s).toFixed(1)+' '+t('كم بخط مستقيم','km straight-line'):''}</div><div class="actions"><a href="https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}" target="_blank" rel="noopener noreferrer">${t('↗ الاتجاهات','↗ Directions')}</a><button data-report="${s.id}">${t('إبلاغ عن الحالة','Report status')}</button></div></article>`).join(''):`<div class="empty"><h3>${t('لا توجد محطات مطابقة','No matching stations')}</h3><p>${t('جرّب تغيير البحث أو إزالة بعض الفلاتر.','Try another search or remove some filters.')}</p><button id="clearFilters">${t('مسح الفلاتر','Clear filters')}</button></div>`;
$('opsStats').innerHTML=stat(open.length+'/'+stations.length,t('المحطات المفتوحة','Open stations'))+stat(Math.round(open.reduce((a,s)=>a+s.wait,0)/open.length),t('متوسط الانتظار / دقيقة','Mean wait / minutes'))+stat(saved.reports.length,t('بلاغات محلية غير مراجعة','Local unreviewed reports'))+stat(stale.length,t('بيانات قديمة','Stale updates'));
$('alerts').innerHTML=stations.filter(s=>!s.open||s.wait>30||age(s)>30).map(s=>`<div class="attention"><b>${esc(name(s))}</b><span>${[!s.open?t('مغلقة','Closed'):'',s.wait>30?t('ازدحام مرتفع','Long queue'):'',age(s)>30?t('تحديث قديم','Stale update'):''].filter(Boolean).join(' · ')}</span></div>`).join('')||t('لا توجد تنبيهات','No alerts');renderReports();scenario();}
function renderReports(){$('reportList').innerHTML=saved.reports.length?saved.reports.slice().reverse().map(r=>{const s=stations.find(s=>s.id===r.station);return `<article class="report"><div class="section-heading"><b>${esc(s?name(s):'—')}</b><span class="pill">${t('محفوظ محلياً · غير مُرسل','Saved locally · Not sent')}</span></div><p>${esc(r.details)}</p><small>${esc(r.id)} · ${new Date(r.created).toLocaleString(lang==='ar'?'ar-LY':'en-GB')} · ${esc(typeLabel(r.type))}</small></article>`;}).join(''):`<div class="empty"><h3>${t('لم تُضف بلاغات بعد','No reports yet')}</h3><p>${t('أضف ملاحظة عن الإغلاق أو توفر الوقود أو الازدحام.','Report an unexpected closure, unavailable fuel or queue problem.')}</p></div>`;}
function typeLabel(type){return {closure:t('إغلاق غير متوقع','Unexpected closure'),fuel:t('نفاد الوقود','Fuel unavailable'),queue:t('ازدحام','Congestion'),other:t('ملاحظة أخرى','Other observation')}[type]||type;}
function scenario(){const change=Number($('supply').value),open=stations.filter(s=>s.open);$('supplyValue').textContent=(change>0?'+':'')+change+'%';$('scenario').textContent=Math.round(open.reduce((a,s)=>a+s.wait,0)/open.length/(1+change/100))+' '+t('دقيقة · انتظار افتراضي','min · illustrative wait');}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('[data-ph-ar]').forEach(el=>el.placeholder=el.dataset[lang==='ar'?'phAr':'phEn']);$('language').textContent=t('English','العربية');const selected=$('reportStation').value;$('reportStation').innerHTML=stations.map(s=>`<option value="${s.id}">${esc(name(s))}</option>`).join('');if(selected)$('reportStation').value=selected;render();}
function openReport(id){$('reportForm').reset();$('reportStation').value=id||stations[0].id;$('reportDialog').showModal();$('reportStation').focus();}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-current',b===button?'page':'false');});document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.tab);}));
$('language').onclick=()=>{lang=lang==='ar'?'en':'ar';translate();};
['search','fuel','sort','openOnly','savedOnly'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='sort'&&$('sort').value==='near'&&!position)notify(t('استخدم زر موقعي لترتيب المحطات حسب المسافة.','Use the location button to sort by distance.'));render();}));
$('cards').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.save){const id=Number(b.dataset.save);saved.favorites=saved.favorites.includes(id)?saved.favorites.filter(n=>n!==id):[...saved.favorites,id];if(!persist())notify(t('تعذر الحفظ الدائم؛ التغيير لهذه الجلسة فقط.','Storage unavailable; this change lasts only for this session.'));render();$('cards').querySelector(`[data-save="${id}"]`)?.focus();}if(b.dataset.report)openReport(Number(b.dataset.report));if(b.id==='clearFilters'){$('search').value='';$('fuel').value='all';$('openOnly').checked=false;$('savedOnly').checked=false;render();}});
$('newReport').onclick=()=>openReport();$('closeDialog').onclick=()=>$('reportDialog').close();
$('reportForm').onsubmit=e=>{e.preventDefault();const details=$('details').value.trim();if(details.length<10){$('details').setCustomValidity(t('اكتب ١٠ أحرف على الأقل.','Enter at least 10 characters.'));$('details').reportValidity();return;}const id='DEMO-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();saved.reports.push({id,station:Number($('reportStation').value),type:$('reportType').value,details,created:Date.now()});const stored=persist();$('reportDialog').close();render();notify(stored?t('حُفظ محلياً، ولم يُرسل: ','Saved locally, not sent: ')+id:t('تعذر التخزين؛ البلاغ محفوظ لهذه الجلسة فقط: ','Storage unavailable; report kept for this session only: ')+id);};$('details').oninput=()=>$('details').setCustomValidity('');
$('locate').onclick=()=>{if(!navigator.geolocation){notify(t('الموقع غير مدعوم في هذا المتصفح.','Geolocation is unavailable in this browser.'));return;}$('locate').disabled=true;navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude};$('sort').value='near';$('locate').disabled=false;render();},()=>{$('locate').disabled=false;notify(t('تعذر تحديد الموقع. اسمح بالوصول أو ابحث بالمنطقة.','Could not get your location. Allow access or search by district.'));},{timeout:12000,maximumAge:60000});};
$('supply').oninput=scenario;$('print').onclick=()=>window.print();
$('export').onclick=()=>{const rows=[['DEMO DATA - NOT LIVE','Station','District','Open','Gasoline95','Diesel','Wait_minutes','Sample_timestamp'],...stations.map(s=>['DEMO',name(s),s['area_'+lang],s.open,s.gas95,s.diesel,s.wait??'',new Date(s.timestamp).toISOString()])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='waqood-demo-stations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
persist();translate();if(!storageOK)notify(t('التخزين المحلي غير متاح. البيانات لهذه الجلسة فقط.','Local storage unavailable. Changes last only for this session.'));setInterval(render,60000);
